modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/CreativeMD/OpticManager/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="opticmanager"
    logoFile="opticmanager.png"
    version="1.2.2"
    displayName="OpticManager"
    displayURL="https://modrinth.com/mod/opticmanager"
    displayTest="MATCH_VERSION"
    authors="CreativeMD"
    description='''Sync client side configurations. Modify length of day and night.'''

[[dependencies.opticmanager]]
    modId="forge"
    mandatory=true
    versionRange="[40.2.14,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.opticmanager]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.opticmanager]]
   modId="creativecore"
   mandatory=true
   ordering="NONE"
   side="BOTH"
   versionRange="2.10.22"

